# Sport Arbitrage: Introduction

In this notebook, I follow the blog poster originaly here:
http://epchan.blogspot.de/2018/01/a-novel-capital-booster-sports-arbitrage.html

In [1]:
### imports
import numpy as np

In [7]:
### define odds and compute probabilities
odds = np.array([[1.4, 1.2, 1.2], [8.8, 9.5, 9.1], [5.8, 6, 6.8]])
probabilities = 1./odds*100

print odds
print probabilities

[[ 1.4  1.2  1.2]
 [ 8.8  9.5  9.1]
 [ 5.8  6.   6.8]]
[[ 71.42857143  83.33333333  83.33333333]
 [ 11.36363636  10.52631579  10.98901099]
 [ 17.24137931  16.66666667  14.70588235]]


Arbitrage opportunity arrises, when the implied probability is less then 100%

Next, we define a function which, once provided the probabilites matrix, computes the implied probability with minimum sum

In [28]:
odds_rows, odds_columns = odds.shape
odds_rows -= 1
odds_columns -= 1



In [30]:
2/18.

0.1111111111111111